clone_folder: C:\dev\workspace\Sky

environment:
  matrix:
    - qt: qt4
      platform: win32

    - qt: qt5
      platform: win32

    - qt: qt5
      platform: win64

install:
  - export LANG=en_US.UTF-8
  - sh 3rdparty.sh %platform%
  - sh configure.sh %qt% %platform%

build_script:
  - sh build.sh %qt% %platform% deploy
