clone_folder: C:\dev\workspace\Sky

environment:
  matrix:
    - qt: qt5
      platform: win64-msvc

install:
  - sh 3rdparty.sh %platform%
  - sh configure.sh %qt% %platform%

build_script:
  - sh build.sh %qt% %platform% deploy
