clone_folder: C:\dev\workspace\Sky

environment:
  matrix:
    - qt: qt4
      platform: win32

    - qt: qt5
      platform: win32

    - qt: qt5
      platform: win64

    - qt: qt5
      platform: win32-msvc

    - qt: qt5
      platform: win64-msvc

build_script:
  - sh environment.sh %platform% %qt% all
  - sh build.sh %platform% all
