#--------------------------------------------------------------------------------------------------
# Windows
#--------------------------------------------------------------------------------------------------

jobs:
- job: win32_qt5
  pool:
    vmImage: "windows-latest"
  steps:
  - bash: |
      sh 3rdparty.sh win32
      sh configure.sh qt5 win32
      sh build.sh qt5 win32 deploy
      cd deploy
      7z a ../Sky.zip *
  - publish: $(System.DefaultWorkingDirectory)/Sky.zip
    artifact: Sky-win32-qt5

#--------------------------------------------------------------------------------------------------

- job: win64_qt5
  pool:
    vmImage: "windows-latest"
  steps:
  - bash: |
      sh 3rdparty.sh win64
      sh configure.sh qt5 win64
      sh build.sh qt5 win64 deploy
      cd deploy
      7z a ../Sky.zip *
  - publish: $(System.DefaultWorkingDirectory)/Sky.zip
    artifact: Sky-win64-qt5

#--------------------------------------------------------------------------------------------------
# macOS
#--------------------------------------------------------------------------------------------------

- job: macOS_qt5
  pool:
    vmImage: "macOS-latest"
  steps:
  - bash: |
      sh 3rdparty.sh macOS
      sh configure.sh qt5 macOS
      sh build.sh qt5 macOS deploy
      cd deploy
      zip -rq ../Sky.zip *
  - publish: $(System.DefaultWorkingDirectory)/Sky.zip
    artifact: Sky-macOS-qt5

#--------------------------------------------------------------------------------------------------
# Linux
#--------------------------------------------------------------------------------------------------

- job: linux32_qt5
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - bash: |
      docker run -d --name ubuntu -v $PWD:/Sky i386/ubuntu:18.04 tail -f /dev/null
      docker exec -t ubuntu bash -c "cd /Sky;
                                     apt-get update;
                                     apt-get -y install sudo curl zip git;
                                     sh 3rdparty.sh linux;
                                     sh configure.sh qt5 linux;
                                     sh build.sh qt5 linux deploy;
                                     cd deploy;
                                     zip -rq ../Sky.zip *"
  - publish: $(System.DefaultWorkingDirectory)/Sky.zip
    artifact: Sky-linux32-qt5

#--------------------------------------------------------------------------------------------------

- job: linux64_qt5
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - bash: |
      docker run -d --name ubuntu -v $PWD:/Sky amd64/ubuntu:18.04 tail -f /dev/null
      docker exec -t ubuntu bash -c "cd /Sky;
                                     apt-get update;
                                     apt-get -y install sudo curl zip git;
                                     sh 3rdparty.sh linux;
                                     sh configure.sh qt5 linux;
                                     sh build.sh qt5 linux deploy;
                                     cd deploy;
                                     zip -rq ../Sky.zip *"
  - publish: $(System.DefaultWorkingDirectory)/Sky.zip
    artifact: Sky-linux64-qt5

#--------------------------------------------------------------------------------------------------
# Android
#--------------------------------------------------------------------------------------------------

- job: android_qt5
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - bash: |
      docker run -d --name ubuntu -v $PWD:/Sky amd64/ubuntu:18.04 tail -f /dev/null
      docker exec -t ubuntu bash -c "cd /Sky;
                                     apt-get update;
                                     apt-get -y install sudo curl zip unzip git;
                                     sh 3rdparty.sh linux;
                                     sh 3rdparty.sh android;
                                     sh configure.sh qt5 android;
                                     sh build.sh qt5 android deploy;
                                     cd deploy;
                                     zip -rq ../Sky.zip *"
  - publish: $(System.DefaultWorkingDirectory)/Sky.zip
    artifact: Sky-android-qt5
