#--------------------------------------------------------------------------------------------------
# Windows
#--------------------------------------------------------------------------------------------------

jobs:
- job: win32_qt4
  pool:
    vmImage: "windows-latest"
  steps:
  - bash: |
      cd ..
      curl -L -o 3rdparty.zip --retry 3 http://omega.gg/get/Sky/3rdparty/win32
      unzip 3rdparty.zip
      cd s
      sh configure.sh qt4 win32
      sh build.sh qt4 win32 deploy
  - publish: $(System.DefaultWorkingDirectory)/deploy
    artifact: Sky-win32-qt4

- job: win32_qt5
  pool:
    vmImage: "windows-latest"
  steps:
  - bash: |
      cd ..
      curl -L -o 3rdparty.zip --retry 3 http://omega.gg/get/Sky/3rdparty/win32
      unzip 3rdparty.zip
      cd s
      sh configure.sh qt5 win32
      sh build.sh qt5 win32 deploy
  - publish: $(System.DefaultWorkingDirectory)/deploy
    artifact: Sky-win32-qt5

#--------------------------------------------------------------------------------------------------

- job: win64_qt5
  pool:
    vmImage: "windows-latest"
  steps:
  - bash: |
      cd ..
      curl -L -o 3rdparty.zip --retry 3 http://omega.gg/get/Sky/3rdparty/win64
      unzip 3rdparty.zip
      cd s
      sh configure.sh qt5 win64
      sh build.sh qt5 win64 deploy
  - publish: $(System.DefaultWorkingDirectory)/deploy
    artifact: Sky-win64-qt5

#--------------------------------------------------------------------------------------------------
# macOS
#--------------------------------------------------------------------------------------------------

- job: macOS_qt5
  pool:
    vmImage: "macOS-latest"
  steps:
  - bash: |
      cd ..
      curl -L -o 3rdparty.zip --retry 3 http://omega.gg/get/Sky/3rdparty/macOS
      unzip 3rdparty.zip
      cd s
      sh configure.sh qt5 macOS
      sh build.sh qt5 macOS deploy
  - publish: $(System.DefaultWorkingDirectory)/deploy
    artifact: Sky-macOS-qt5

#--------------------------------------------------------------------------------------------------
# Linux
#--------------------------------------------------------------------------------------------------

- job: linux32_qt4
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - bash: |
      docker run -d --name ubuntu -v $PWD:/Sky i386/ubuntu:18.04 tail -f /dev/null
      docker exec -t ubuntu bash -c "cd /Sky;
                                     apt-get update;
                                     apt-get -y install sudo wget;
                                     sh 3rdparty.sh all qt4 ubuntu;
                                     sh configure.sh qt4 linux;
                                     sh build.sh qt4 linux deploy"
  - publish: $(System.DefaultWorkingDirectory)/deploy
    artifact: Sky-linux32-qt4

- job: linux32_qt5
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - bash: |
      docker run -d --name ubuntu -v $PWD:/Sky i386/ubuntu:18.04 tail -f /dev/null
      docker exec -t ubuntu bash -c "cd /Sky;
                                     apt-get update;
                                     apt-get -y install sudo wget;
                                     sh 3rdparty.sh all qt5 ubuntu;
                                     sh configure.sh qt5 linux;
                                     sh build.sh qt5 linux deploy"
  - publish: $(System.DefaultWorkingDirectory)/deploy
    artifact: Sky-linux32-qt5

#--------------------------------------------------------------------------------------------------

- job: linux64_qt4
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - bash: |
      docker run -d --name ubuntu -v $PWD:/Sky amd64/ubuntu:18.04 tail -f /dev/null
      docker exec -t ubuntu bash -c "cd /Sky;
                                     apt-get update;
                                     apt-get -y install sudo wget;
                                     sh 3rdparty.sh all qt4 ubuntu;
                                     sh configure.sh qt4 linux;
                                     sh build.sh qt4 linux deploy"
  - publish: $(System.DefaultWorkingDirectory)/deploy
    artifact: Sky-linux64-qt4

- job: linux64_qt5
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - bash: |
      docker run -d --name ubuntu -v $PWD:/Sky amd64/ubuntu:18.04 tail -f /dev/null
      docker exec -t ubuntu bash -c "cd /Sky;
                                     apt-get update;
                                     apt-get -y install sudo wget;
                                     sh 3rdparty.sh all qt5 ubuntu;
                                     sh configure.sh qt5 linux;
                                     sh build.sh qt5 linux deploy"
  - publish: $(System.DefaultWorkingDirectory)/deploy
    artifact: Sky-linux64-qt5
