sudo: required

services:
  - docker

language: cpp

matrix:
  include:
    - os: linux
      env: QT=qt4 TARGET=i386
    - os: linux
      env: QT=qt4 TARGET=amd64
    - os: linux
      env: QT=qt5 TARGET=i386
    - os: linux
      env: QT=qt5 TARGET=amd64

before_install:
  - docker run -d --name ubuntu -v $PWD:/Sky ${TARGET}/ubuntu:18.04 tail -f /dev/null

install:
  - docker exec -t ubuntu bash -c "cd /Sky;
                                   apt-get update;
                                   apt-get -y install sudo wget;
                                   sh 3rdparty.sh all ${QT} ubuntu;
                                   sh configure.sh ${QT} linux"

script:
  - docker exec -t ubuntu bash -c "cd /Sky;
                                   sh build.sh ${QT} linux deploy"
