dist: trusty
sudo: required

services: docker

language: cpp
compiler: gcc

matrix:
  include:
    - env: DIST=ubuntu TARGET==xenial-i386
    - env: DIST=ubuntu TARGET==xenial-amd64

install:
  - sh 3rdparty.sh all ubuntu
  - sh configure.sh qt4 linux

script: sh build.sh qt4 linux deploy
