matrix:
  include:
    - dist: trusty
      sudo: required
      compiler: gcc
      env:
        - $Qt="4"
    - dist: trusty
      sudo: required
      compiler: gcc
      env:
        - $Qt="5"

script:
  - if [ $Qt = "4" ]; then sh 3rdparty.sh all ubuntu fi
  - if [ $Qt = "4" ]; sh build.sh qt4 linux deploy fi
