sudo: required
dist: trusty

services:
  - docker

language: cpp
#compiler: gcc

matrix:
  include:
    - os: linux
      env: DIST=ubuntu TARGET==xenial-i386 PACKAGE=deb
    - os: linux
      env: DIST=ubuntu TARGET==xenial-amd64 PACKAGE=deb

install:
  - sh 3rdparty.sh all ubuntu
  - sh configure.sh qt4 linux

script: sh build.sh qt4 linux deploy
