sudo: required

services:
  - docker

language: cpp

matrix:
  include:
    - os: linux
      env: QT=qt4 TARGET=i386
    - os: linux
      env: QT=qt4 TARGET=amd64
    - os: linux
      env: QT=qt5 TARGET=i386
    - os: linux
      env: QT=qt5 TARGET=amd64

script:
  - docker run -d --name ubuntu -v $PWD:/Sky ${TARGET}/ubuntu:18.04 tail -f /dev/null
  - docker exec -t ubuntu bash -c "cd /Sky;
                                   apt-get update;
                                   apt-get -y install sudo curl git;
                                   sh environment.sh mingw ${QT} 3rdparty;
                                   sh 3rdparty.sh linux;
                                   sh configure.sh ${QT} linux;
                                   sh build.sh ${QT} linux deploy"
