sudo: required

services:
  - docker

language: cpp

matrix:
  include:
    - env: DIST=ubuntu TARGET==xenial-i386
    #- env: DIST=ubuntu TARGET==xenial-amd64

before_install:
  - docker run -d --name ubuntu-test -v $(pwd):/travis ubuntu:17.10 tail -f /dev/null
  - docker ps

install:
  - docker exec -t ubuntu-test bash -c "cd /travis;
                                        apt-get update;
                                        apt-get -y install sudo;
                                        sh 3rdparty.sh all ubuntu;
                                        sh configure.sh qt4 linux"

script:
  - docker exec -t ubuntu-test bash -c "cd /travis;
                                        sh build.sh qt4 linux deploy"
