sudo: required

services:
  - docker

language: cpp

matrix:
  include:
    - os: linux
      env: TARGET==i386
    #- os: linux
    #  env: TARGET==amd64

before_install:
  - docker run -d --name ubuntu -v $(pwd):/travis ubuntu:17.10 tail -f /dev/null
  - docker ps

install:
  - docker exec -t ubuntu bash -c "cd /travis;
                                   apt-get update;
                                   apt-get -y install sudo wget;
                                   sh 3rdparty.sh all ubuntu;
                                   sh configure.sh qt4 linux"

script:
  - docker exec -t ubuntu bash -c "cd /travis;
                                   sh build.sh qt4 linux deploy"
