sudo: required

services:
  - docker

language: cpp

matrix:
  include:
    - env: TARGET==xenial-i386
    #- env: TARGET==xenial-amd64

before_install:
  - docker run --name ubuntu -d -v $(pwd):/dev ubuntu:latest tail -f /dev/null
  - docker ps

install:
  - docker exec -t ubuntu bash -c "cd /dev;
                                   sh 3rdparty.sh all ubuntu;
                                   sh configure.sh qt4 linux"

script:
  - docker exec -t ubuntu bash -c "cd /dev;
                                   sh build.sh qt4 linux deploy"
