dist: trusty
sudo: required

compiler: gcc

matrix:
  include:
    env:
      - $Qt="4"

script:
  - if [ $Qt = "4" ]; then sh 3rdparty.sh all ubuntu fi
  - if [ $Qt = "4" ]; sh build.sh qt4 linux deploy fi
