sudo: required

services:
  - docker

language: cpp

matrix:
  include:
    - os: linux
      env: OS==ubuntu TARGET==i386 QT=qt4
    - os: linux
      env: OS==ubuntu TARGET==amd64 QT=qt4

before_install:
  - docker run -d --name ubuntu -v $(pwd):/travis ${TARGET}/ubuntu:17.10 tail -f /dev/null
  - docker ps

install:
  - docker exec -t ubuntu bash -c "cd /travis;
                                   apt-get update;
                                   apt-get -y install sudo wget;
                                   sh 3rdparty.sh all ubuntu;
                                   sh configure.sh ${QT} linux"

script:
  - docker exec -t ubuntu bash -c "cd /travis;
                                   sh build.sh ${QT} linux deploy"
